### ISSUE TITLE
Create release action failed

### ISSUE THREAD

**Issue by lmarz** [KhronosGroup/OpenCL-SDK#115]
See https://github.com/KhronosGroup/OpenCL-SDK/actions/runs/11519948784

**Comment by bashbaug** [comment]
Thanks, we noticed this too, and we're working on it.

I'll keep this issue open for tracking until it's fixed.

**Comment by bashbaug** [comment]
Hi - thank you for your patience.

The release action is fixed, and I just published it as the latest release.  Please let us know if you find any additional issues - thanks!
