### ISSUE TITLE
Difficulties with launching OpenGL samples with latest changes to InteropWindow infrastructure

### ISSUE THREAD

**Issue by shajder** [KhronosGroup/OpenCL-SDK#116]
@Beanavil I wasn't able to launch OpenGL samples (neither `nbody` nor `conway`) with the latest updates. The error message is:

> OpenCL Utils error: Selected device isn't interoperable with the current OpenGL context.

I've tried with `nvidia` and `intel` platform with the same outcome. It looks like creating OpenCL context fails. My OS is Ubuntu 22.04

Additional remark: I verified similar interop GL samples from @bashbaug repo and it works just fine so I am assuming something may be wrong with recent corrections to InteropWindow infrastructure.

**Comment by bashbaug** [comment]
FWIW, this works fine on my Ubuntu 22.04 system.  I do see this output:

```sh
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 3.3 ; depth bits = 32 ; stencil bits = 0 ; AA level = 0 ; core = true ; debug = false ; sRGB = false
Created: version = 3.3 ; depth bits = 24 ; stencil bits = 0 ; AA level = 0 ; core = true ; debug = false ; sRGB = false
```

But the interop context and buffers are created just fine.

**Comment by shajder** [comment]
Yes, I just confirmed on other machine GL samples works. This is clearly problem with Ubuntu configuration - X11 chooses intel which is not prime platform for my display. Thus, closing the issue!
