### ISSUE TITLE
CMake files for Windows are incomplete.

### ISSUE THREAD

**Issue by kingc8** [KhronosGroup/OpenCL-SDK#15]
CMake Error at CMakeLists.txt:38 (add_subdirectory):
  The source directory

    C:/Users/MasonStorm/Downloads/OpenCL-SDK-main/external/OpenCL-ICD-Loader

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:41 (set_target_properties):
  set_target_properties Can not find target to add properties to: OpenCL

Configuring incomplete, errors occurred!

-----
Best regards.

**Comment by MathiasMagnus** [comment]
You've cloned the repo without --recursive. There is WIP to make this process more failsafe by the scripts doing it on your behalf if you forget. In the meantime, [see here](https://github.com/KhronosGroup/OpenCL-SDK#setting-up-the-sdk) or [here](https://stackoverflow.com/a/4438292/1476661). Let us know if it solved the problem.

**Comment by kingc8** [comment]
Ok, well, I'll do it another way. I just clicked on "clone" downloaded as a zip, unzipped it into Downloads folder.
I then open Cmake GUI and set the source directory as a the root directory of the OpenCL-SDK and created a folder in the root folder called "build" as a target location for the build process.

Is that really not going to work?

**Comment by kingc8** [comment]
Indeed,
 git clone --recursive https://github.com/KhronosGroup/OpenCL-SDK.git
on the Powershell fetches everything.

Thanks a lot.

Closing issue.
