### ISSUE TITLE
This repository has no CLA

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-SDK#20]
This repository has no CLA enabled.  I suspect that was an oversight, I can't recall discussion around this repository not having one nor find anything around that in meeting minutes.

**Comment by neiltrevett** [comment]
@outofcontrol James - please add standard Khronos Apache 2.0 CLA - thanks!

**Comment by outofcontrol** [comment]
It's public now! Awesome. CLA has been added.

**Comment by outofcontrol** [comment]
Khronos members who's company has signed the Khronos CLA are exempt from needing to sign it again on GitHub. So if a member doesn't see the CLA, this is most likely why.

**Comment by alycm** [comment]
Thanks for fixing this!
