### ISSUE TITLE
Enhance CMake function to add samples

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-SDK#22]
See @bashbaug's suggestions on https://github.com/KhronosGroup/OpenCL-SDK/pull/21#pullrequestreview-567539782.

**Comment by bashbaug** [comment]
I can take care of this.

Are there any desired changes or additions to the proposal, or should I port it over as-is?

**Comment by kpet** [comment]
After a quick look I'd say I'm not convinced about the usefulness of `TEST` (do we really need configurability per sample?) and `NUMBER` (looks like a maintenance headache but I might have missed the point of it) but everything else looks like options we'll definitely want IMHO.
