### ISSUE TITLE
[question] OpenCLUtils_Export.h

### ISSUE THREAD

**Issue by zjin-lcf** [KhronosGroup/OpenCL-SDK#48]
Where is OpenCLUtils_Export.h located ?  Thanks.

**Comment by MathiasMagnus** [comment]
OpenCLUtils_Export.h is created by the build. It is a stock export header generated by CMake. You can find one instance in your build tree after configuring or in any of the binary release archives under `include/CL/Utils/OpenCLUitls_Export.h`.
